// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: message.sql

package database

import (
	"context"
)

const sendMessage = `-- name: SendMessage :one
INSERT INTO messages (id, send_at, sender_id, receiver_id, content) 
VALUES (
   $1, 
   NOW(),
   $2,
   $3,
   $4
)
RETURNING id, sent_at, sender_id, receiver_id, content
`

type SendMessageParams struct {
	ID         int32
	SenderID   string
	ReceiverID string
	Content    string
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, sendMessage,
		arg.ID,
		arg.SenderID,
		arg.ReceiverID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SentAt,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
	)
	return i, err
}
