// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, email, password, username, subscribers, subscribed_to, is_premium, verification_code, verification_expire_time, is_verified FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.Username,
		pq.Array(&i.Subscribers),
		pq.Array(&i.SubscribedTo),
		&i.IsPremium,
		&i.VerificationCode,
		&i.VerificationExpireTime,
		&i.IsVerified,
	)
	return i, err
}
