
services:
  server:
    build:
      context: .
      target: final
    ports:
      - 50055:50055

  rabbitmq:
    image: 
      rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

